name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: ["14.15"]
        angular: ["~12.0.0", "~12.1.0", "~12.2.0", "~13.0.0"]
        typescript: ["~4.2.2", "~4.4.4"]

        exclude:

          - angular: "~12.0.0"
            typescript: "~4.4.4"

          - angular: "~12.1.0"
            typescript: "~4.4.4"

          - angular: "~12.2.0"
            typescript: "~4.4.4"

          - angular: "~13.0.0"
            typescript: "~4.2.2"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
        cache: npm

    - name: Install dependencies (${{ matrix.angular }}, ${{ matrix.typescript }})
      run: npm install

    - run: npm install @angular/common@${{ matrix.angular }}
    - run: npm install @angular/compiler@${{ matrix.angular }}
    - run: npm install @angular/compiler-cli@${{ matrix.angular }}
    - run: npm install @angular/core@${{ matrix.angular }}
    - run: npm install @angular/platform-browser@${{ matrix.angular }}
    - run: npm install @angular/platform-browser-dynamic@${{ matrix.angular }}
    - run: npm install typescript@${{ matrix.typescript }}

    - name: Run tests
      run: npm run test-ci

    - name: Build library
      run: npm run build
